version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cliapp
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    network_mode: service:db

volumes:
  postgres-data:
